// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `dial_impl`, `dial_libp2p_webrtc_server_blocking`, `wait_for_chat_response`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `BehaviourEvent`, `Behaviour`, `ChatOutcome`, `ChatRequest`, `ChatResponse`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_fields_are_eq`, `assert_fields_are_eq`, `clone`, `clone`, `clone`, `clone`, `eq`, `eq`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `handle_established_inbound_connection`, `handle_established_outbound_connection`, `handle_pending_inbound_connection`, `handle_pending_outbound_connection`, `on_connection_handler_event`, `on_swarm_event`, `poll`

Future<Libp2pWebRtcDialResult> dialLibp2PWebrtcServer({
  required Libp2pWebRtcDialRequest request,
}) => RustLib.instance.api.crateApiLibp2PWebrtcDialLibp2PWebrtcServer(
  request: request,
);

class Libp2pWebRtcDialRequest {
  final String serverMultiaddr;
  final int timeoutSeconds;
  final String message;

  const Libp2pWebRtcDialRequest({
    required this.serverMultiaddr,
    required this.timeoutSeconds,
    required this.message,
  });

  @override
  int get hashCode =>
      serverMultiaddr.hashCode ^ timeoutSeconds.hashCode ^ message.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Libp2pWebRtcDialRequest &&
          runtimeType == other.runtimeType &&
          serverMultiaddr == other.serverMultiaddr &&
          timeoutSeconds == other.timeoutSeconds &&
          message == other.message;
}

class Libp2pWebRtcDialResult {
  final String localPeerId;
  final String remotePeerId;
  final String dialedMultiaddr;
  final String sentMessage;
  final String echoedMessage;
  final String serverTimestamp;
  final String statusMessage;
  final String explanation;

  const Libp2pWebRtcDialResult({
    required this.localPeerId,
    required this.remotePeerId,
    required this.dialedMultiaddr,
    required this.sentMessage,
    required this.echoedMessage,
    required this.serverTimestamp,
    required this.statusMessage,
    required this.explanation,
  });

  @override
  int get hashCode =>
      localPeerId.hashCode ^
      remotePeerId.hashCode ^
      dialedMultiaddr.hashCode ^
      sentMessage.hashCode ^
      echoedMessage.hashCode ^
      serverTimestamp.hashCode ^
      statusMessage.hashCode ^
      explanation.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Libp2pWebRtcDialResult &&
          runtimeType == other.runtimeType &&
          localPeerId == other.localPeerId &&
          remotePeerId == other.remotePeerId &&
          dialedMultiaddr == other.dialedMultiaddr &&
          sentMessage == other.sentMessage &&
          echoedMessage == other.echoedMessage &&
          serverTimestamp == other.serverTimestamp &&
          statusMessage == other.statusMessage &&
          explanation == other.explanation;
}
