import 'dart:async';
import 'dart:typed_data';
import 'dart:ui' as ui;

import 'package:auto_route/auto_route.dart';
import 'package:flutter/material.dart';
import 'package:super_clipboard/super_clipboard.dart';

@RoutePage()
class SuperClipboardPage extends StatefulWidget {
  const SuperClipboardPage({super.key});

  @override
  State<SuperClipboardPage> createState() => _SuperClipboardPageState();
}

class _SuperClipboardPageState extends State<SuperClipboardPage> {
  final TextEditingController _plainTextController = TextEditingController(
    text: 'Flutter + super_clipboard plain text payload',
  );
  final TextEditingController _htmlTextController = TextEditingController(
    text: 'Rich clipboard payload generated by super_clipboard.',
  );
  final TextEditingController _uriController = TextEditingController(
    text: 'https://pub.dev/packages/super_clipboard',
  );

  String _statusMessage = 'Ready to read or write clipboard content.';
  String _lastPlainText = 'Nothing pasted yet.';
  String _lastHtmlText = 'No HTML content inspected yet.';
  String _lastUri = 'No URI content inspected yet.';
  List<String> _availableFormats = <String>[];
  Uint8List? _lastImageBytes;
  int _lastItemCount = 0;
  bool _lastImageSynthesized = false;
  String _pasteEventSummary =
      'No browser paste event received yet. Press Ctrl/Cmd + V on web.';

  @override
  void initState() {
    super.initState();
    ClipboardEvents.instance?.registerPasteEventListener(_onPasteEvent);
  }

  @override
  void dispose() {
    ClipboardEvents.instance?.unregisterPasteEventListener(_onPasteEvent);
    _plainTextController.dispose();
    _htmlTextController.dispose();
    _uriController.dispose();
    super.dispose();
  }

  bool get _clipboardAvailable => SystemClipboard.instance != null;
  bool get _browserPasteEventsAvailable => ClipboardEvents.instance != null;

  Future<void> _onPasteEvent(ClipboardReadEvent event) async {
    final ClipboardReader reader = await event.getClipboardReader();
    await _readFromReader(
      reader,
      sourceDescription: 'Browser paste event captured.',
    );
  }

  Future<void> _copyTextAndHtml() async {
    await _runClipboardWrite(
      successMessage: 'Copied plain text + HTML representations.',
      action: () async {
        final DataWriterItem item = DataWriterItem();
        item.add(
          Formats.htmlText(
            '<h3>super_clipboard</h3>'
            '<p>${_htmlTextController.text.trim()}</p>'
            '<p><em>Written from Flutter.</em></p>',
          ),
        );
        item.add(Formats.plainText(_plainTextController.text.trim()));
        await SystemClipboard.instance!.write(<DataWriterItem>[item]);
      },
    );
  }

  Future<void> _copyLazyText() async {
    await _runClipboardWrite(
      successMessage: 'Copied lazy text providers to clipboard.',
      action: () async {
        final DataWriterItem item = DataWriterItem();
        item.add(
          Formats.htmlText.lazy(() {
            return '<strong>Lazy HTML</strong><br/>Resolved at ${DateTime.now()}';
          }),
        );
        item.add(
          Formats.plainText.lazy(() {
            return 'Lazy plain text resolved at ${DateTime.now()}';
          }),
        );
        await SystemClipboard.instance!.write(<DataWriterItem>[item]);
      },
    );
  }

  Future<void> _copyUri() async {
    await _runClipboardWrite(
      successMessage: 'Copied URI payload with display name.',
      action: () async {
        final Uri uri = Uri.parse(_uriController.text.trim());
        final DataWriterItem item = DataWriterItem();
        item.add(
          Formats.uri(NamedUri(uri, name: 'super_clipboard package page')),
        );
        item.add(Formats.plainText(uri.toString()));
        await SystemClipboard.instance!.write(<DataWriterItem>[item]);
      },
    );
  }

  Future<void> _copyImage() async {
    await _runClipboardWrite(
      successMessage: 'Copied generated PNG image to clipboard.',
      action: () async {
        final Uint8List imageBytes = await _buildDemoImage();
        final DataWriterItem item = DataWriterItem(
          suggestedName: 'super_clipboard_demo.png',
        );
        item.add(Formats.png(imageBytes));
        item.add(Formats.plainText('Generated PNG copied from Flutter.'));
        await SystemClipboard.instance!.write(<DataWriterItem>[item]);
      },
    );
  }

  Future<void> _copyMultipleRepresentations() async {
    await _runClipboardWrite(
      successMessage: 'Copied text, HTML, URI, and PNG representations.',
      action: () async {
        final Uri uri = Uri.parse(_uriController.text.trim());
        final Uint8List imageBytes = await _buildDemoImage();
        final DataWriterItem item = DataWriterItem(
          suggestedName: 'super_clipboard_multi.png',
        );
        item.add(Formats.plainText(_plainTextController.text.trim()));
        item.add(
          Formats.htmlText(
            '<p><strong>Composite payload</strong> from Flutter.</p>',
          ),
        );
        item.add(Formats.uri(NamedUri(uri, name: 'Open super_clipboard docs')));
        item.add(Formats.png(imageBytes));
        await SystemClipboard.instance!.write(<DataWriterItem>[item]);
      },
    );
  }

  Future<void> _pasteFromClipboard() async {
    final SystemClipboard? clipboard = SystemClipboard.instance;
    if (clipboard == null) {
      _setStatus(
        'SystemClipboard is not available on this platform. Use browser paste events on web instead.',
      );
      return;
    }

    try {
      final ClipboardReader reader = await clipboard.read();
      await _readFromReader(
        reader,
        sourceDescription: 'Read clipboard through SystemClipboard.read().',
      );
    } catch (error) {
      _setStatus('Clipboard read failed: $error');
    }
  }

  Future<void> _readFromReader(
    ClipboardReader reader, {
    required String sourceDescription,
  }) async {
    final List<String> available = <String>[
      if (reader.canProvide(Formats.plainText)) 'plainText',
      if (reader.canProvide(Formats.htmlText)) 'htmlText',
      if (reader.canProvide(Formats.uri)) 'uri',
      if (reader.canProvide(Formats.png)) 'png',
    ];

    final String? plainText = reader.canProvide(Formats.plainText)
        ? await reader.readValue(Formats.plainText)
        : null;
    final String? htmlText = reader.canProvide(Formats.htmlText)
        ? await reader.readValue(Formats.htmlText)
        : null;
    final NamedUri? namedUri = reader.canProvide(Formats.uri)
        ? await reader.readValue(Formats.uri)
        : null;

    Uint8List? imageBytes;
    bool imageSynthesized = false;
    if (reader.canProvide(Formats.png)) {
      imageSynthesized = reader.isSynthesized(Formats.png);
      final Completer<Uint8List?> completer = Completer<Uint8List?>();
      final ReadProgress? progress = reader.getFile(
        Formats.png,
        (DataReaderFile file) async {
          completer.complete(await file.readAll());
        },
        onError: (Object error) {
          if (!completer.isCompleted) {
            completer.completeError(error);
          }
        },
      );
      if (progress != null) {
        imageBytes = await completer.future;
      }
    }

    if (!mounted) {
      return;
    }

    setState(() {
      _availableFormats = available;
      _lastPlainText = plainText ?? 'No plain text representation available.';
      _lastHtmlText = htmlText ?? 'No HTML representation available.';
      _lastUri = namedUri == null
          ? 'No URI representation available.'
          : '${namedUri.name ?? 'Link'} -> ${namedUri.uri}';
      _lastImageBytes = imageBytes;
      _lastItemCount = reader.items.length;
      _lastImageSynthesized = imageSynthesized;
      _statusMessage = sourceDescription;
      _pasteEventSummary =
          '$sourceDescription Items: ${reader.items.length}. Formats: ${available.join(', ')}';
    });
  }

  Future<void> _runClipboardWrite({
    required String successMessage,
    required Future<void> Function() action,
  }) async {
    if (!_clipboardAvailable) {
      _setStatus(
        'SystemClipboard is not available on this platform. Browser clipboard events are only exposed on web.',
      );
      return;
    }

    try {
      await action();
      _setStatus(successMessage);
    } catch (error) {
      _setStatus('Clipboard write failed: $error');
    }
  }

  void _setStatus(String message) {
    if (!mounted) {
      return;
    }

    setState(() {
      _statusMessage = message;
    });
    ScaffoldMessenger.of(
      context,
    ).showSnackBar(SnackBar(content: Text(message)));
  }

  Future<Uint8List> _buildDemoImage() async {
    final ui.PictureRecorder recorder = ui.PictureRecorder();
    final Canvas canvas = Canvas(recorder);
    const Size size = Size(240, 140);
    final Rect rect = Offset.zero & size;

    final Paint background = Paint()
      ..shader = ui.Gradient.linear(rect.topLeft, rect.bottomRight, <Color>[
        const Color(0xFF0B4F6C),
        const Color(0xFF01BAEF),
      ]);
    canvas.drawRRect(
      RRect.fromRectAndRadius(rect, const Radius.circular(24)),
      background,
    );

    canvas.drawCircle(
      const Offset(52, 42),
      22,
      Paint()..color = Colors.white.withValues(alpha: 0.20),
    );
    canvas.drawCircle(
      const Offset(188, 98),
      30,
      Paint()..color = Colors.black.withValues(alpha: 0.12),
    );

    final ui.ParagraphBuilder builder =
        ui.ParagraphBuilder(
            ui.ParagraphStyle(fontSize: 20, fontWeight: FontWeight.w700),
          )
          ..pushStyle(
            ui.TextStyle(color: Colors.white, fontWeight: FontWeight.w700),
          )
          ..addText('super_clipboard');
    final ui.Paragraph heading = builder.build()
      ..layout(const ui.ParagraphConstraints(width: 190));
    canvas.drawParagraph(heading, const Offset(24, 28));

    final ui.ParagraphBuilder subBuilder =
        ui.ParagraphBuilder(
            ui.ParagraphStyle(fontSize: 12, fontWeight: FontWeight.w500),
          )
          ..pushStyle(ui.TextStyle(color: Colors.white.withValues(alpha: 0.92)))
          ..addText('Flutter clipboard demo\ntext + HTML + URI + PNG');
    final ui.Paragraph sub = subBuilder.build()
      ..layout(const ui.ParagraphConstraints(width: 190));
    canvas.drawParagraph(sub, const Offset(24, 64));

    final ui.Image image = await recorder.endRecording().toImage(
      size.width.toInt(),
      size.height.toInt(),
    );
    final ByteData? byteData = await image.toByteData(
      format: ui.ImageByteFormat.png,
    );
    return byteData!.buffer.asUint8List();
  }

  @override
  Widget build(BuildContext context) {
    final ThemeData theme = Theme.of(context);
    final ColorScheme colorScheme = theme.colorScheme;

    return Scaffold(
      appBar: AppBar(title: const Text('super_clipboard Module')),
      body: SelectionArea(
        child: ListView(
          padding: const EdgeInsets.all(24),
          children: <Widget>[
            Text(
              'Use `super_clipboard` when you need richer clipboard support than plain text: multiple representations, HTML snippets, URIs, images, and browser paste events.',
              style: theme.textTheme.titleMedium?.copyWith(
                fontWeight: FontWeight.w600,
              ),
            ),
            const SizedBox(height: 20),
            _SectionCard(
              title: 'Capability Summary',
              child: Wrap(
                spacing: 12,
                runSpacing: 12,
                children: <Widget>[
                  _InfoChip(
                    label: 'SystemClipboard',
                    value: _clipboardAvailable ? 'available' : 'unavailable',
                  ),
                  _InfoChip(
                    label: 'ClipboardEvents',
                    value: _browserPasteEventsAvailable
                        ? 'web listener ready'
                        : 'not available',
                  ),
                  _InfoChip(label: 'Last item count', value: '$_lastItemCount'),
                  _InfoChip(
                    label: 'Last image synthesized',
                    value: '$_lastImageSynthesized',
                  ),
                ],
              ),
            ),
            const SizedBox(height: 16),
            _SectionCard(
              title: 'Write Text And HTML',
              child: Column(
                crossAxisAlignment: CrossAxisAlignment.start,
                children: <Widget>[
                  TextField(
                    controller: _plainTextController,
                    maxLines: 2,
                    decoration: const InputDecoration(
                      labelText: 'Plain text representation',
                      border: OutlineInputBorder(),
                    ),
                  ),
                  const SizedBox(height: 12),
                  TextField(
                    controller: _htmlTextController,
                    maxLines: 3,
                    decoration: const InputDecoration(
                      labelText: 'Rich text content',
                      border: OutlineInputBorder(),
                    ),
                  ),
                  const SizedBox(height: 16),
                  Wrap(
                    spacing: 12,
                    runSpacing: 12,
                    children: <Widget>[
                      FilledButton(
                        onPressed: _copyTextAndHtml,
                        child: const Text('Write Text + HTML'),
                      ),
                      OutlinedButton(
                        onPressed: _copyLazyText,
                        child: const Text('Write Lazy Text'),
                      ),
                    ],
                  ),
                ],
              ),
            ),
            const SizedBox(height: 16),
            _SectionCard(
              title: 'Write URI And PNG',
              child: Column(
                crossAxisAlignment: CrossAxisAlignment.start,
                children: <Widget>[
                  TextField(
                    controller: _uriController,
                    decoration: const InputDecoration(
                      labelText: 'URI payload',
                      border: OutlineInputBorder(),
                    ),
                  ),
                  const SizedBox(height: 16),
                  Wrap(
                    spacing: 12,
                    runSpacing: 12,
                    children: <Widget>[
                      FilledButton(
                        onPressed: _copyUri,
                        child: const Text('Write URI'),
                      ),
                      FilledButton.tonal(
                        onPressed: _copyImage,
                        child: const Text('Write PNG'),
                      ),
                      OutlinedButton(
                        onPressed: _copyMultipleRepresentations,
                        child: const Text('Write Composite Item'),
                      ),
                    ],
                  ),
                ],
              ),
            ),
            const SizedBox(height: 16),
            _SectionCard(
              title: 'Read Clipboard',
              child: Column(
                crossAxisAlignment: CrossAxisAlignment.start,
                children: <Widget>[
                  FilledButton(
                    onPressed: _pasteFromClipboard,
                    child: const Text('Read Clipboard'),
                  ),
                  const SizedBox(height: 16),
                  _ResultCard(
                    label: 'Available formats',
                    value: _availableFormats.isEmpty
                        ? 'None detected yet.'
                        : _availableFormats.join(', '),
                  ),
                  const SizedBox(height: 12),
                  _ResultCard(label: 'Plain text', value: _lastPlainText),
                  const SizedBox(height: 12),
                  _ResultCard(label: 'HTML text', value: _lastHtmlText),
                  const SizedBox(height: 12),
                  _ResultCard(label: 'URI', value: _lastUri),
                  if (_lastImageBytes != null) ...<Widget>[
                    const SizedBox(height: 12),
                    Text('PNG preview', style: theme.textTheme.labelLarge),
                    const SizedBox(height: 8),
                    ClipRRect(
                      borderRadius: BorderRadius.circular(16),
                      child: Image.memory(
                        _lastImageBytes!,
                        height: 140,
                        fit: BoxFit.contain,
                      ),
                    ),
                  ],
                ],
              ),
            ),
            const SizedBox(height: 16),
            _SectionCard(
              title: 'Browser Paste Events',
              child: DecoratedBox(
                decoration: BoxDecoration(
                  color: colorScheme.surfaceContainerHighest,
                  borderRadius: BorderRadius.circular(16),
                ),
                child: Padding(
                  padding: const EdgeInsets.all(16),
                  child: Text(
                    _browserPasteEventsAvailable
                        ? 'This page is listening for browser paste events. Focus the page and press Ctrl/Cmd + V to inspect clipboard contents without the usual asynchronous read prompt.\n\nLast event: $_pasteEventSummary'
                        : 'ClipboardEvents are only exposed on web. On mobile and desktop use the explicit "Read Clipboard" action instead.',
                  ),
                ),
              ),
            ),
            const SizedBox(height: 16),
            _SectionCard(
              title: 'Notes',
              child: Column(
                crossAxisAlignment: CrossAxisAlignment.start,
                children: const <Widget>[
                  Text(
                    'Write both `Formats.plainText` and `Formats.htmlText` when copying rich text. Android expects a plain-text fallback.',
                  ),
                  SizedBox(height: 8),
                  Text(
                    'PNG is the preferred image format. The package transparently adapts image formats for some platforms.',
                  ),
                  SizedBox(height: 8),
                  Text(
                    'On Android, richer clipboard payloads such as images and custom data require the `DataProvider` manifest entry.',
                  ),
                ],
              ),
            ),
            const SizedBox(height: 16),
            _ResultCard(label: 'Status', value: _statusMessage),
          ],
        ),
      ),
      floatingActionButton: FloatingActionButton.extended(
        onPressed: () => context.router.replacePath('/'),
        icon: const Icon(Icons.home),
        label: const Text('Home'),
      ),
    );
  }
}

class _SectionCard extends StatelessWidget {
  const _SectionCard({required this.title, required this.child});

  final String title;
  final Widget child;

  @override
  Widget build(BuildContext context) {
    final ThemeData theme = Theme.of(context);

    return Card(
      clipBehavior: Clip.antiAlias,
      child: Padding(
        padding: const EdgeInsets.all(16),
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: <Widget>[
            Text(
              title,
              style: theme.textTheme.titleMedium?.copyWith(
                fontWeight: FontWeight.w700,
              ),
            ),
            const SizedBox(height: 12),
            child,
          ],
        ),
      ),
    );
  }
}

class _ResultCard extends StatelessWidget {
  const _ResultCard({required this.label, required this.value});

  final String label;
  final String value;

  @override
  Widget build(BuildContext context) {
    final ColorScheme colorScheme = Theme.of(context).colorScheme;

    return DecoratedBox(
      decoration: BoxDecoration(
        color: colorScheme.surfaceContainerHighest,
        borderRadius: BorderRadius.circular(16),
      ),
      child: Padding(
        padding: const EdgeInsets.all(16),
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: <Widget>[
            Text(label, style: Theme.of(context).textTheme.labelLarge),
            const SizedBox(height: 8),
            Text(value),
          ],
        ),
      ),
    );
  }
}

class _InfoChip extends StatelessWidget {
  const _InfoChip({required this.label, required this.value});

  final String label;
  final String value;

  @override
  Widget build(BuildContext context) {
    return Chip(
      label: Text('$label: $value'),
      visualDensity: VisualDensity.compact,
    );
  }
}
