import 'package:auto_route/auto_route.dart';
import 'package:flutter/foundation.dart';
import 'package:flutter/material.dart';
import 'package:video_thumbnail/video_thumbnail.dart';

const String _sampleVideoUrl =
    'https://flutter.github.io/assets-for-api-docs/assets/videos/butterfly.mp4';

class _ThumbnailFrame {
  const _ThumbnailFrame({
    required this.timeMs,
    required this.bytes,
    required this.label,
  });

  final int timeMs;
  final Uint8List bytes;
  final String label;
}

@RoutePage(name: 'VideoThumbnailRoute')
class VideoThumbnailPage extends StatefulWidget {
  const VideoThumbnailPage({super.key});

  @override
  State<VideoThumbnailPage> createState() => _VideoThumbnailPageState();
}

class _VideoThumbnailPageState extends State<VideoThumbnailPage> {
  ImageFormat _imageFormat = ImageFormat.PNG;
  int _quality = 80;
  int _maxWidth = 220;
  int _focusTimeMs = 1200;
  late Future<List<_ThumbnailFrame>> _framesFuture;

  bool get _isSupportedPlatform {
    if (kIsWeb) {
      return false;
    }

    return defaultTargetPlatform == TargetPlatform.android ||
        defaultTargetPlatform == TargetPlatform.iOS;
  }

  @override
  void initState() {
    super.initState();
    _framesFuture = _loadFrames();
  }

  Future<List<_ThumbnailFrame>> _loadFrames() async {
    if (!_isSupportedPlatform) {
      return const <_ThumbnailFrame>[];
    }

    final List<int> requestTimes = <int>{
      0,
      _focusTimeMs,
      (_focusTimeMs + 1400).clamp(0, 5000),
    }.toList()..sort();

    final List<_ThumbnailFrame> frames = <_ThumbnailFrame>[];
    for (final int timeMs in requestTimes) {
      final Uint8List? bytes = await VideoThumbnail.thumbnailData(
        video: _sampleVideoUrl,
        headers: const <String, String>{'User-Agent': 'widget-layout-example2'},
        imageFormat: _imageFormat,
        maxWidth: _maxWidth,
        timeMs: timeMs,
        quality: _quality,
      );

      if (bytes == null) {
        throw StateError('video_thumbnail returned null data for $timeMs ms.');
      }

      frames.add(
        _ThumbnailFrame(
          timeMs: timeMs,
          bytes: bytes,
          label: '${(timeMs / 1000).toStringAsFixed(1)}s',
        ),
      );
    }

    return frames;
  }

  void _refreshFrames() {
    setState(() {
      _framesFuture = _loadFrames();
    });
  }

  @override
  Widget build(BuildContext context) {
    final ThemeData theme = Theme.of(context);

    return Scaffold(
      appBar: AppBar(title: const Text('video_thumbnail Module')),
      body: ListView(
        padding: const EdgeInsets.all(24),
        children: <Widget>[
          Text(
            'Generate thumbnail images from local files or remote video URLs',
            style: theme.textTheme.headlineSmall?.copyWith(
              fontWeight: FontWeight.w800,
            ),
          ),
          const SizedBox(height: 12),
          Text(
            '`video_thumbnail` is a native plugin for extracting preview frames '
            'from video sources. This page demonstrates `thumbnailData`, '
            '`ImageFormat`, `timeMs`, `quality`, `maxWidth`, request headers, '
            'and the related `thumbnailFile` workflow in code samples.',
            style: theme.textTheme.bodyLarge,
          ),
          const SizedBox(height: 24),
          const _CodeSampleCard(
            title: 'Generate bytes for Image.memory',
            code: r'''
final bytes = await VideoThumbnail.thumbnailData(
  video: videoUrl,
  imageFormat: ImageFormat.PNG,
  maxWidth: 220,
  timeMs: 1200,
  quality: 80,
);

if (bytes != null) {
  return Image.memory(bytes);
}
''',
          ),
          const SizedBox(height: 16),
          const _CodeSampleCard(
            title: 'Write thumbnail file',
            code: r'''
final filePath = await VideoThumbnail.thumbnailFile(
  video: videoUrl,
  thumbnailPath: temporaryDirectory.path,
  imageFormat: ImageFormat.WEBP,
  maxHeight: 120,
  quality: 75,
);
''',
          ),
          const SizedBox(height: 16),
          const _CodeSampleCard(
            title: 'Asset-video pattern',
            code: r'''
final byteData = await rootBundle.load('assets/my_video.mp4');
final tempVideo = File('${tempDir.path}/my_video.mp4')
  ..createSync(recursive: true)
  ..writeAsBytesSync(byteData.buffer.asUint8List());

final thumbnail = await VideoThumbnail.thumbnailFile(
  video: tempVideo.path,
  imageFormat: ImageFormat.PNG,
);
''',
          ),
          const SizedBox(height: 24),
          _SectionCard(
            title: 'Live Demo: Network MP4 -> thumbnail bytes',
            description:
                'This demo targets the package\'s supported platforms in this '
                'project: Android and iOS. The generated bytes are rendered '
                'with `Image.memory`.',
            child: Column(
              crossAxisAlignment: CrossAxisAlignment.start,
              children: <Widget>[
                Container(
                  width: double.infinity,
                  padding: const EdgeInsets.all(16),
                  decoration: BoxDecoration(
                    color: theme.colorScheme.surfaceContainerHighest.withValues(
                      alpha: 0.45,
                    ),
                    borderRadius: BorderRadius.circular(18),
                  ),
                  child: Text(
                    'Source video: $_sampleVideoUrl',
                    style: theme.textTheme.bodyMedium,
                  ),
                ),
                const SizedBox(height: 16),
                if (!_isSupportedPlatform)
                  const _UnsupportedPanel()
                else ...<Widget>[
                  DropdownButtonFormField<ImageFormat>(
                    initialValue: _imageFormat,
                    decoration: const InputDecoration(
                      labelText: 'Image format',
                      border: OutlineInputBorder(),
                    ),
                    items: ImageFormat.values.map((ImageFormat format) {
                      return DropdownMenuItem<ImageFormat>(
                        value: format,
                        child: Text(format.name),
                      );
                    }).toList(),
                    onChanged: (ImageFormat? value) {
                      if (value == null) {
                        return;
                      }
                      setState(() {
                        _imageFormat = value;
                      });
                    },
                  ),
                  const SizedBox(height: 16),
                  Text(
                    'Quality: $_quality',
                    style: theme.textTheme.titleMedium?.copyWith(
                      fontWeight: FontWeight.w700,
                    ),
                  ),
                  Slider(
                    value: _quality.toDouble(),
                    min: 10,
                    max: 100,
                    divisions: 18,
                    label: '$_quality',
                    onChanged: (double value) {
                      setState(() {
                        _quality = value.round();
                      });
                    },
                  ),
                  Text(
                    'Max width: $_maxWidth px',
                    style: theme.textTheme.titleMedium?.copyWith(
                      fontWeight: FontWeight.w700,
                    ),
                  ),
                  Slider(
                    value: _maxWidth.toDouble(),
                    min: 96,
                    max: 320,
                    divisions: 14,
                    label: '$_maxWidth',
                    onChanged: (double value) {
                      setState(() {
                        _maxWidth = value.round();
                      });
                    },
                  ),
                  Text(
                    'Focus timestamp: ${(_focusTimeMs / 1000).toStringAsFixed(1)}s',
                    style: theme.textTheme.titleMedium?.copyWith(
                      fontWeight: FontWeight.w700,
                    ),
                  ),
                  Slider(
                    value: _focusTimeMs.toDouble(),
                    min: 0,
                    max: 4500,
                    divisions: 18,
                    label: '${_focusTimeMs}ms',
                    onChanged: (double value) {
                      setState(() {
                        _focusTimeMs = value.round();
                      });
                    },
                  ),
                  Wrap(
                    spacing: 12,
                    runSpacing: 12,
                    children: <Widget>[
                      FilledButton.icon(
                        onPressed: _refreshFrames,
                        icon: const Icon(Icons.refresh),
                        label: const Text('Generate Thumbnails'),
                      ),
                      ActionChip(
                        label: const Text('0.0s'),
                        onPressed: () {
                          setState(() {
                            _focusTimeMs = 0;
                          });
                          _refreshFrames();
                        },
                      ),
                      ActionChip(
                        label: const Text('1.2s'),
                        onPressed: () {
                          setState(() {
                            _focusTimeMs = 1200;
                          });
                          _refreshFrames();
                        },
                      ),
                      ActionChip(
                        label: const Text('2.8s'),
                        onPressed: () {
                          setState(() {
                            _focusTimeMs = 2800;
                          });
                          _refreshFrames();
                        },
                      ),
                    ],
                  ),
                  const SizedBox(height: 18),
                  FutureBuilder<List<_ThumbnailFrame>>(
                    future: _framesFuture,
                    builder:
                        (
                          BuildContext context,
                          AsyncSnapshot<List<_ThumbnailFrame>> snapshot,
                        ) {
                          if (snapshot.connectionState ==
                              ConnectionState.waiting) {
                            return const Padding(
                              padding: EdgeInsets.all(24),
                              child: Center(child: CircularProgressIndicator()),
                            );
                          }

                          if (snapshot.hasError) {
                            return _ErrorPanel(error: snapshot.error);
                          }

                          final List<_ThumbnailFrame> frames =
                              snapshot.data ?? const <_ThumbnailFrame>[];

                          return Wrap(
                            spacing: 16,
                            runSpacing: 16,
                            children: frames.map((final _ThumbnailFrame frame) {
                              return _ThumbnailPreviewCard(
                                frame: frame,
                                format: _imageFormat,
                              );
                            }).toList(),
                          );
                        },
                  ),
                ],
              ],
            ),
          ),
        ],
      ),
      floatingActionButton: FloatingActionButton.extended(
        onPressed: () => context.router.replacePath('/'),
        icon: const Icon(Icons.home),
        label: const Text('Home'),
      ),
    );
  }
}

class _ThumbnailPreviewCard extends StatelessWidget {
  const _ThumbnailPreviewCard({required this.frame, required this.format});

  final _ThumbnailFrame frame;
  final ImageFormat format;

  @override
  Widget build(BuildContext context) {
    final ThemeData theme = Theme.of(context);

    return SizedBox(
      width: 230,
      child: Card(
        clipBehavior: Clip.antiAlias,
        child: Padding(
          padding: const EdgeInsets.all(16),
          child: Column(
            crossAxisAlignment: CrossAxisAlignment.start,
            children: <Widget>[
              ClipRRect(
                borderRadius: BorderRadius.circular(16),
                child: Image.memory(
                  frame.bytes,
                  height: 128,
                  width: double.infinity,
                  fit: BoxFit.cover,
                ),
              ),
              const SizedBox(height: 12),
              Text(
                'Frame at ${frame.label}',
                style: theme.textTheme.titleMedium?.copyWith(
                  fontWeight: FontWeight.w700,
                ),
              ),
              const SizedBox(height: 6),
              Text('timeMs: ${frame.timeMs}'),
              Text('format: ${format.name}'),
              Text('bytes: ${frame.bytes.length}'),
            ],
          ),
        ),
      ),
    );
  }
}

class _UnsupportedPanel extends StatelessWidget {
  const _UnsupportedPanel();

  @override
  Widget build(BuildContext context) {
    return Container(
      width: double.infinity,
      padding: const EdgeInsets.all(18),
      decoration: BoxDecoration(
        color: Colors.amber.withValues(alpha: 0.12),
        borderRadius: BorderRadius.circular(18),
        border: Border.all(color: Colors.amber.withValues(alpha: 0.24)),
      ),
      child: const Text(
        'The live thumbnail generator is disabled here because '
        '`video_thumbnail` in this project only exposes Android and iOS '
        'platform implementations. The code samples above still show the API.',
      ),
    );
  }
}

class _ErrorPanel extends StatelessWidget {
  const _ErrorPanel({required this.error});

  final Object? error;

  @override
  Widget build(BuildContext context) {
    return Container(
      width: double.infinity,
      padding: const EdgeInsets.all(18),
      decoration: BoxDecoration(
        color: Colors.red.withValues(alpha: 0.08),
        borderRadius: BorderRadius.circular(18),
        border: Border.all(color: Colors.red.withValues(alpha: 0.18)),
      ),
      child: Text('Thumbnail generation failed.\n$error'),
    );
  }
}

class _SectionCard extends StatelessWidget {
  const _SectionCard({
    required this.title,
    required this.child,
    this.description,
  });

  final String title;
  final String? description;
  final Widget child;

  @override
  Widget build(BuildContext context) {
    final ThemeData theme = Theme.of(context);

    return Card(
      clipBehavior: Clip.antiAlias,
      child: Padding(
        padding: const EdgeInsets.all(20),
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: <Widget>[
            Text(
              title,
              style: theme.textTheme.titleLarge?.copyWith(
                fontWeight: FontWeight.w800,
              ),
            ),
            if (description case final String description) ...<Widget>[
              const SizedBox(height: 8),
              Text(description, style: theme.textTheme.bodyMedium),
            ],
            const SizedBox(height: 18),
            child,
          ],
        ),
      ),
    );
  }
}

class _CodeSampleCard extends StatelessWidget {
  const _CodeSampleCard({required this.title, required this.code});

  final String title;
  final String code;

  @override
  Widget build(BuildContext context) {
    final ThemeData theme = Theme.of(context);

    return Card(
      clipBehavior: Clip.antiAlias,
      child: Padding(
        padding: const EdgeInsets.all(20),
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: <Widget>[
            Text(
              title,
              style: theme.textTheme.titleMedium?.copyWith(
                fontWeight: FontWeight.w800,
              ),
            ),
            const SizedBox(height: 12),
            Container(
              width: double.infinity,
              padding: const EdgeInsets.all(16),
              decoration: BoxDecoration(
                color: theme.colorScheme.surfaceContainerHighest.withValues(
                  alpha: 0.65,
                ),
                borderRadius: BorderRadius.circular(18),
              ),
              child: Text(
                code.trim(),
                style: theme.textTheme.bodyMedium?.copyWith(
                  fontFamily: 'monospace',
                  height: 1.5,
                ),
              ),
            ),
          ],
        ),
      ),
    );
  }
}
