// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/ethereum.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({required RustLibApi api}) {
    instance.initMockImpl(api: api);
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {
    await api.crateApiEthereumInitApp();
  }

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.12.0';

  @override
  int get rustContentHash => -1729505472;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
        stem: 'rust_lib_widget_layout_example2',
        ioDirectory: 'rust/target/release/',
        webPrefix: 'pkg/',
        wasmBindgenName: 'wasm_bindgen',
      );
}

abstract class RustLibApi extends BaseApi {
  Future<EthereumDemoResult> crateApiEthereumFetchEthereumDemo({
    required EthereumDemoRequest request,
  });

  Future<void> crateApiEthereumInitApp();
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  Future<EthereumDemoResult> crateApiEthereumFetchEthereumDemo({
    required EthereumDemoRequest request,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_box_autoadd_ethereum_demo_request(request, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 1,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_ethereum_demo_result,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiEthereumFetchEthereumDemoConstMeta,
        argValues: [request],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiEthereumFetchEthereumDemoConstMeta =>
      const TaskConstMeta(
        debugName: "fetch_ethereum_demo",
        argNames: ["request"],
      );

  @override
  Future<void> crateApiEthereumInitApp() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 2,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiEthereumInitAppConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiEthereumInitAppConstMeta =>
      const TaskConstMeta(debugName: "init_app", argNames: []);

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  EthereumDemoRequest dco_decode_box_autoadd_ethereum_demo_request(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_ethereum_demo_request(raw);
  }

  @protected
  EthereumDemoRequest dco_decode_ethereum_demo_request(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return EthereumDemoRequest(
      rpcUrl: dco_decode_String(arr[0]),
      walletAddress: dco_decode_String(arr[1]),
      erc20TokenAddress: dco_decode_String(arr[2]),
    );
  }

  @protected
  EthereumDemoResult dco_decode_ethereum_demo_result(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 11)
      throw Exception('unexpected arr length: expect 11 but see ${arr.length}');
    return EthereumDemoResult(
      chainRpcUrl: dco_decode_String(arr[0]),
      walletAddress: dco_decode_String(arr[1]),
      latestBlockNumber: dco_decode_String(arr[2]),
      nativeBalanceWei: dco_decode_String(arr[3]),
      nativeBalanceEth: dco_decode_String(arr[4]),
      tokenAddress: dco_decode_String(arr[5]),
      tokenSymbol: dco_decode_String(arr[6]),
      tokenDecimals: dco_decode_u_8(arr[7]),
      tokenBalanceRaw: dco_decode_String(arr[8]),
      tokenBalanceFormatted: dco_decode_String(arr[9]),
      explanation: dco_decode_String(arr[10]),
    );
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  EthereumDemoRequest sse_decode_box_autoadd_ethereum_demo_request(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_ethereum_demo_request(deserializer));
  }

  @protected
  EthereumDemoRequest sse_decode_ethereum_demo_request(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_rpcUrl = sse_decode_String(deserializer);
    var var_walletAddress = sse_decode_String(deserializer);
    var var_erc20TokenAddress = sse_decode_String(deserializer);
    return EthereumDemoRequest(
      rpcUrl: var_rpcUrl,
      walletAddress: var_walletAddress,
      erc20TokenAddress: var_erc20TokenAddress,
    );
  }

  @protected
  EthereumDemoResult sse_decode_ethereum_demo_result(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_chainRpcUrl = sse_decode_String(deserializer);
    var var_walletAddress = sse_decode_String(deserializer);
    var var_latestBlockNumber = sse_decode_String(deserializer);
    var var_nativeBalanceWei = sse_decode_String(deserializer);
    var var_nativeBalanceEth = sse_decode_String(deserializer);
    var var_tokenAddress = sse_decode_String(deserializer);
    var var_tokenSymbol = sse_decode_String(deserializer);
    var var_tokenDecimals = sse_decode_u_8(deserializer);
    var var_tokenBalanceRaw = sse_decode_String(deserializer);
    var var_tokenBalanceFormatted = sse_decode_String(deserializer);
    var var_explanation = sse_decode_String(deserializer);
    return EthereumDemoResult(
      chainRpcUrl: var_chainRpcUrl,
      walletAddress: var_walletAddress,
      latestBlockNumber: var_latestBlockNumber,
      nativeBalanceWei: var_nativeBalanceWei,
      nativeBalanceEth: var_nativeBalanceEth,
      tokenAddress: var_tokenAddress,
      tokenSymbol: var_tokenSymbol,
      tokenDecimals: var_tokenDecimals,
      tokenBalanceRaw: var_tokenBalanceRaw,
      tokenBalanceFormatted: var_tokenBalanceFormatted,
      explanation: var_explanation,
    );
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_box_autoadd_ethereum_demo_request(
    EthereumDemoRequest self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_ethereum_demo_request(self, serializer);
  }

  @protected
  void sse_encode_ethereum_demo_request(
    EthereumDemoRequest self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.rpcUrl, serializer);
    sse_encode_String(self.walletAddress, serializer);
    sse_encode_String(self.erc20TokenAddress, serializer);
  }

  @protected
  void sse_encode_ethereum_demo_result(
    EthereumDemoResult self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.chainRpcUrl, serializer);
    sse_encode_String(self.walletAddress, serializer);
    sse_encode_String(self.latestBlockNumber, serializer);
    sse_encode_String(self.nativeBalanceWei, serializer);
    sse_encode_String(self.nativeBalanceEth, serializer);
    sse_encode_String(self.tokenAddress, serializer);
    sse_encode_String(self.tokenSymbol, serializer);
    sse_encode_u_8(self.tokenDecimals, serializer);
    sse_encode_String(self.tokenBalanceRaw, serializer);
    sse_encode_String(self.tokenBalanceFormatted, serializer);
    sse_encode_String(self.explanation, serializer);
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }
}
