import 'package:assorted_layout_widgets/assorted_layout_widgets.dart';
import 'package:flutter/material.dart';

import '../widgets/demo_scaffold.dart';

class TextFittingPage extends StatefulWidget {
  const TextFittingPage({super.key});

  @override
  State<TextFittingPage> createState() => _TextFittingPageState();
}

class _TextFittingPageState extends State<TextFittingPage> {
  double _lineWidth = 280;

  @override
  Widget build(BuildContext context) {
    return DemoPageScaffold(
      title: 'SideBySide + FitHorizontally',
      subtitle:
          'These widgets help dense labels and metadata rows stay readable '
          'instead of overflowing abruptly.',
      accent: const Color(0xFFBE123C),
      children: <Widget>[
        DemoSection(
          title: 'Responsive metadata rows',
          description:
              '`SideBySide` lets the first children keep what they need '
              'while the last child uses the remaining width.',
          child: Column(
            crossAxisAlignment: CrossAxisAlignment.start,
            children: <Widget>[
              Text('Available width: ${_lineWidth.round()} px'),
              Slider(
                value: _lineWidth,
                min: 180,
                max: 420,
                divisions: 12,
                label: _lineWidth.round().toString(),
                onChanged: (double value) {
                  setState(() {
                    _lineWidth = value;
                  });
                },
              ),
              const SizedBox(height: 10),
              _exampleCard(
                label: 'SideBySide header',
                child: SizedBox(
                  width: _lineWidth,
                  child: SideBySide(
                    gaps: const <double>[10, 12],
                    minEndChildWidth: 90,
                    children: <Widget>[
                      const Text(
                        'Quarterly release readiness review',
                        maxLines: 1,
                        overflow: TextOverflow.ellipsis,
                        textWidthBasis: TextWidthBasis.longestLine,
                        style: TextStyle(
                          fontSize: 18,
                          fontWeight: FontWeight.w700,
                        ),
                      ),
                      const Text(
                        'Owner: Platform',
                        maxLines: 1,
                        overflow: TextOverflow.ellipsis,
                        textWidthBasis: TextWidthBasis.longestLine,
                      ),
                      Align(
                        alignment: Alignment.centerRight,
                        child: Box(
                          color: const Color(0xFFFFE4E6),
                          padding: const Pad(horizontal: 10, vertical: 8),
                          child: const Text(
                            'At risk',
                            style: TextStyle(fontWeight: FontWeight.w700),
                          ),
                        ),
                      ),
                    ],
                  ),
                ),
              ),
            ],
          ),
        ),
        DemoSection(
          title: 'Shrink only horizontally',
          description:
              '`FitHorizontally` is useful for single-line titles that '
              'should compress before they clip.',
          child: Column(
            crossAxisAlignment: CrossAxisAlignment.start,
            children: <Widget>[
              _exampleCard(
                label: 'Plain text',
                child: SizedBox(
                  width: _lineWidth,
                  child: const Text(
                    'Autogenerated diagnostics summary for staging deployment',
                    maxLines: 1,
                    overflow: TextOverflow.fade,
                    softWrap: false,
                    style: TextStyle(fontSize: 22, fontWeight: FontWeight.w700),
                  ),
                ),
              ),
              const SizedBox(height: 12),
              _exampleCard(
                label: 'FitHorizontally(shrinkLimit: 0.55)',
                child: SizedBox(
                  width: _lineWidth,
                  child: const FitHorizontally(
                    shrinkLimit: 0.55,
                    alignment: Alignment.centerLeft,
                    child: Text(
                      'Autogenerated diagnostics summary for staging deployment',
                      maxLines: 1,
                      overflow: TextOverflow.fade,
                      softWrap: false,
                      style: TextStyle(
                        fontSize: 22,
                        fontWeight: FontWeight.w700,
                      ),
                    ),
                  ),
                ),
              ),
            ],
          ),
        ),
      ],
    );
  }

  Widget _exampleCard({required String label, required Widget child}) {
    return Container(
      padding: const EdgeInsets.all(14),
      decoration: BoxDecoration(
        color: const Color(0xFFFFF1F2),
        borderRadius: BorderRadius.circular(18),
        border: Border.all(color: const Color(0xFFFBCFE8)),
      ),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: <Widget>[
          Text(label, style: const TextStyle(fontWeight: FontWeight.w700)),
          const SizedBox(height: 12),
          child,
        ],
      ),
    );
  }
}
