// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

#![allow(
    non_camel_case_types,
    unused,
    non_snake_case,
    clippy::needless_return,
    clippy::redundant_closure_call,
    clippy::redundant_closure,
    clippy::useless_conversion,
    clippy::unit_arg,
    clippy::unused_unit,
    clippy::double_parens,
    clippy::let_and_return,
    clippy::too_many_arguments,
    clippy::match_single_binding,
    clippy::clone_on_copy,
    clippy::let_unit_value,
    clippy::deref_addrof,
    clippy::explicit_auto_deref,
    clippy::borrow_deref_ref,
    clippy::uninlined_format_args,
    clippy::needless_borrow
)]

// Section: imports

use flutter_rust_bridge::for_generated::byteorder::{NativeEndian, ReadBytesExt, WriteBytesExt};
use flutter_rust_bridge::for_generated::{Lifetimeable, Lockable, transform_result_dco};
use flutter_rust_bridge::{Handler, IntoIntoDart};

// Section: boilerplate

flutter_rust_bridge::frb_generated_boilerplate!(
    default_stream_sink_codec = SseCodec,
    default_rust_opaque = RustOpaqueMoi,
    default_rust_auto_opaque = RustAutoOpaqueMoi,
);
pub(crate) const FLUTTER_RUST_BRIDGE_CODEGEN_VERSION: &str = "2.12.0";
pub(crate) const FLUTTER_RUST_BRIDGE_CODEGEN_CONTENT_HASH: i32 = 1962147472;

// Section: executor

flutter_rust_bridge::frb_generated_default_handler!();

// Section: wire_funcs

fn wire__crate__api__libp2p_webrtc__dial_libp2p_webrtc_server_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_async::<flutter_rust_bridge::for_generated::SseCodec, _, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "dial_libp2p_webrtc_server",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_request =
                <crate::api::libp2p_webrtc::Libp2pWebRtcDialRequest>::sse_decode(&mut deserializer);
            deserializer.end();
            move |context| async move {
                transform_result_sse::<_, String>(
                    (move || async move {
                        let output_ok =
                            crate::api::libp2p_webrtc::dial_libp2p_webrtc_server(api_request)
                                .await?;
                        Ok(output_ok)
                    })()
                    .await,
                )
            }
        },
    )
}
fn wire__crate__api__ethereum__fetch_ethereum_demo_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_async::<flutter_rust_bridge::for_generated::SseCodec, _, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "fetch_ethereum_demo",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_request =
                <crate::api::ethereum::EthereumDemoRequest>::sse_decode(&mut deserializer);
            deserializer.end();
            move |context| async move {
                transform_result_sse::<_, String>(
                    (move || async move {
                        let output_ok =
                            crate::api::ethereum::fetch_ethereum_demo(api_request).await?;
                        Ok(output_ok)
                    })()
                    .await,
                )
            }
        },
    )
}
fn wire__crate__api__solana__fetch_solana_demo_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_async::<flutter_rust_bridge::for_generated::SseCodec, _, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "fetch_solana_demo",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_request =
                <crate::api::solana::SolanaDemoRequest>::sse_decode(&mut deserializer);
            deserializer.end();
            move |context| async move {
                transform_result_sse::<_, String>(
                    (move || async move {
                        let output_ok = crate::api::solana::fetch_solana_demo(api_request).await?;
                        Ok(output_ok)
                    })()
                    .await,
                )
            }
        },
    )
}
fn wire__crate__api__sui__fetch_sui_demo_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_async::<flutter_rust_bridge::for_generated::SseCodec, _, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "fetch_sui_demo",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_request = <crate::api::sui::SuiDemoRequest>::sse_decode(&mut deserializer);
            deserializer.end();
            move |context| async move {
                transform_result_sse::<_, String>(
                    (move || async move {
                        let output_ok = crate::api::sui::fetch_sui_demo(api_request).await?;
                        Ok(output_ok)
                    })()
                    .await,
                )
            }
        },
    )
}
fn wire__crate__api__ethereum__init_app_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "init_app",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            deserializer.end();
            move |context| {
                transform_result_sse::<_, ()>((move || {
                    let output_ok = Result::<_, ()>::Ok({
                        crate::api::ethereum::init_app();
                    })?;
                    Ok(output_ok)
                })())
            }
        },
    )
}

// Section: dart2rust

impl SseDecode for String {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut inner = <Vec<u8>>::sse_decode(deserializer);
        return String::from_utf8(inner).unwrap();
    }
}

impl SseDecode for crate::api::ethereum::EthereumDemoRequest {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_rpcUrl = <String>::sse_decode(deserializer);
        let mut var_walletAddress = <String>::sse_decode(deserializer);
        let mut var_erc20TokenAddress = <String>::sse_decode(deserializer);
        return crate::api::ethereum::EthereumDemoRequest {
            rpc_url: var_rpcUrl,
            wallet_address: var_walletAddress,
            erc20_token_address: var_erc20TokenAddress,
        };
    }
}

impl SseDecode for crate::api::ethereum::EthereumDemoResult {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_chainRpcUrl = <String>::sse_decode(deserializer);
        let mut var_walletAddress = <String>::sse_decode(deserializer);
        let mut var_latestBlockNumber = <String>::sse_decode(deserializer);
        let mut var_nativeBalanceWei = <String>::sse_decode(deserializer);
        let mut var_nativeBalanceEth = <String>::sse_decode(deserializer);
        let mut var_tokenAddress = <String>::sse_decode(deserializer);
        let mut var_tokenSymbol = <String>::sse_decode(deserializer);
        let mut var_tokenDecimals = <u8>::sse_decode(deserializer);
        let mut var_tokenBalanceRaw = <String>::sse_decode(deserializer);
        let mut var_tokenBalanceFormatted = <String>::sse_decode(deserializer);
        let mut var_explanation = <String>::sse_decode(deserializer);
        return crate::api::ethereum::EthereumDemoResult {
            chain_rpc_url: var_chainRpcUrl,
            wallet_address: var_walletAddress,
            latest_block_number: var_latestBlockNumber,
            native_balance_wei: var_nativeBalanceWei,
            native_balance_eth: var_nativeBalanceEth,
            token_address: var_tokenAddress,
            token_symbol: var_tokenSymbol,
            token_decimals: var_tokenDecimals,
            token_balance_raw: var_tokenBalanceRaw,
            token_balance_formatted: var_tokenBalanceFormatted,
            explanation: var_explanation,
        };
    }
}

impl SseDecode for crate::api::libp2p_webrtc::Libp2pWebRtcDialRequest {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_serverMultiaddr = <String>::sse_decode(deserializer);
        let mut var_timeoutSeconds = <u32>::sse_decode(deserializer);
        let mut var_message = <String>::sse_decode(deserializer);
        return crate::api::libp2p_webrtc::Libp2pWebRtcDialRequest {
            server_multiaddr: var_serverMultiaddr,
            timeout_seconds: var_timeoutSeconds,
            message: var_message,
        };
    }
}

impl SseDecode for crate::api::libp2p_webrtc::Libp2pWebRtcDialResult {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_localPeerId = <String>::sse_decode(deserializer);
        let mut var_remotePeerId = <String>::sse_decode(deserializer);
        let mut var_dialedMultiaddr = <String>::sse_decode(deserializer);
        let mut var_sentMessage = <String>::sse_decode(deserializer);
        let mut var_echoedMessage = <String>::sse_decode(deserializer);
        let mut var_serverTimestamp = <String>::sse_decode(deserializer);
        let mut var_statusMessage = <String>::sse_decode(deserializer);
        let mut var_explanation = <String>::sse_decode(deserializer);
        return crate::api::libp2p_webrtc::Libp2pWebRtcDialResult {
            local_peer_id: var_localPeerId,
            remote_peer_id: var_remotePeerId,
            dialed_multiaddr: var_dialedMultiaddr,
            sent_message: var_sentMessage,
            echoed_message: var_echoedMessage,
            server_timestamp: var_serverTimestamp,
            status_message: var_statusMessage,
            explanation: var_explanation,
        };
    }
}

impl SseDecode for Vec<u8> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut len_ = <i32>::sse_decode(deserializer);
        let mut ans_ = Vec::with_capacity(len_ as usize);
        for idx_ in 0..len_ {
            ans_.push(<u8>::sse_decode(deserializer));
        }
        return ans_;
    }
}

impl SseDecode for Option<u64> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        if (<bool>::sse_decode(deserializer)) {
            return Some(<u64>::sse_decode(deserializer));
        } else {
            return None;
        }
    }
}

impl SseDecode for crate::api::solana::SolanaDemoRequest {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_rpcUrl = <String>::sse_decode(deserializer);
        let mut var_walletAddress = <String>::sse_decode(deserializer);
        return crate::api::solana::SolanaDemoRequest {
            rpc_url: var_rpcUrl,
            wallet_address: var_walletAddress,
        };
    }
}

impl SseDecode for crate::api::solana::SolanaDemoResult {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_rpcUrl = <String>::sse_decode(deserializer);
        let mut var_walletAddress = <String>::sse_decode(deserializer);
        let mut var_latestSlot = <u64>::sse_decode(deserializer);
        let mut var_blockHeight = <u64>::sse_decode(deserializer);
        let mut var_epoch = <u64>::sse_decode(deserializer);
        let mut var_transactionCount = <Option<u64>>::sse_decode(deserializer);
        let mut var_lamports = <u64>::sse_decode(deserializer);
        let mut var_solBalance = <String>::sse_decode(deserializer);
        let mut var_commitment = <String>::sse_decode(deserializer);
        let mut var_explanation = <String>::sse_decode(deserializer);
        return crate::api::solana::SolanaDemoResult {
            rpc_url: var_rpcUrl,
            wallet_address: var_walletAddress,
            latest_slot: var_latestSlot,
            block_height: var_blockHeight,
            epoch: var_epoch,
            transaction_count: var_transactionCount,
            lamports: var_lamports,
            sol_balance: var_solBalance,
            commitment: var_commitment,
            explanation: var_explanation,
        };
    }
}

impl SseDecode for crate::api::sui::SuiDemoRequest {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_rpcUrl = <String>::sse_decode(deserializer);
        let mut var_walletAddress = <String>::sse_decode(deserializer);
        return crate::api::sui::SuiDemoRequest {
            rpc_url: var_rpcUrl,
            wallet_address: var_walletAddress,
        };
    }
}

impl SseDecode for crate::api::sui::SuiDemoResult {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_rpcUrl = <String>::sse_decode(deserializer);
        let mut var_walletAddress = <String>::sse_decode(deserializer);
        let mut var_apiVersion = <String>::sse_decode(deserializer);
        let mut var_rpcMethodsCount = <String>::sse_decode(deserializer);
        let mut var_currentEpoch = <String>::sse_decode(deserializer);
        let mut var_referenceGasPrice = <String>::sse_decode(deserializer);
        let mut var_activeValidators = <String>::sse_decode(deserializer);
        let mut var_ownedObjectsInPage = <String>::sse_decode(deserializer);
        let mut var_stakePositionCount = <String>::sse_decode(deserializer);
        let mut var_explanation = <String>::sse_decode(deserializer);
        return crate::api::sui::SuiDemoResult {
            rpc_url: var_rpcUrl,
            wallet_address: var_walletAddress,
            api_version: var_apiVersion,
            rpc_methods_count: var_rpcMethodsCount,
            current_epoch: var_currentEpoch,
            reference_gas_price: var_referenceGasPrice,
            active_validators: var_activeValidators,
            owned_objects_in_page: var_ownedObjectsInPage,
            stake_position_count: var_stakePositionCount,
            explanation: var_explanation,
        };
    }
}

impl SseDecode for u32 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        deserializer.cursor.read_u32::<NativeEndian>().unwrap()
    }
}

impl SseDecode for u64 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        deserializer.cursor.read_u64::<NativeEndian>().unwrap()
    }
}

impl SseDecode for u8 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        deserializer.cursor.read_u8().unwrap()
    }
}

impl SseDecode for () {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {}
}

impl SseDecode for i32 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        deserializer.cursor.read_i32::<NativeEndian>().unwrap()
    }
}

impl SseDecode for bool {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        deserializer.cursor.read_u8().unwrap() != 0
    }
}

fn pde_ffi_dispatcher_primary_impl(
    func_id: i32,
    port: flutter_rust_bridge::for_generated::MessagePort,
    ptr: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len: i32,
    data_len: i32,
) {
    // Codec=Pde (Serialization + dispatch), see doc to use other codecs
    match func_id {
        1 => wire__crate__api__libp2p_webrtc__dial_libp2p_webrtc_server_impl(
            port,
            ptr,
            rust_vec_len,
            data_len,
        ),
        2 => {
            wire__crate__api__ethereum__fetch_ethereum_demo_impl(port, ptr, rust_vec_len, data_len)
        }
        3 => wire__crate__api__solana__fetch_solana_demo_impl(port, ptr, rust_vec_len, data_len),
        4 => wire__crate__api__sui__fetch_sui_demo_impl(port, ptr, rust_vec_len, data_len),
        5 => wire__crate__api__ethereum__init_app_impl(port, ptr, rust_vec_len, data_len),
        _ => unreachable!(),
    }
}

fn pde_ffi_dispatcher_sync_impl(
    func_id: i32,
    ptr: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len: i32,
    data_len: i32,
) -> flutter_rust_bridge::for_generated::WireSyncRust2DartSse {
    // Codec=Pde (Serialization + dispatch), see doc to use other codecs
    match func_id {
        _ => unreachable!(),
    }
}

// Section: rust2dart

// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::ethereum::EthereumDemoRequest {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.rpc_url.into_into_dart().into_dart(),
            self.wallet_address.into_into_dart().into_dart(),
            self.erc20_token_address.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::ethereum::EthereumDemoRequest
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::ethereum::EthereumDemoRequest>
    for crate::api::ethereum::EthereumDemoRequest
{
    fn into_into_dart(self) -> crate::api::ethereum::EthereumDemoRequest {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::ethereum::EthereumDemoResult {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.chain_rpc_url.into_into_dart().into_dart(),
            self.wallet_address.into_into_dart().into_dart(),
            self.latest_block_number.into_into_dart().into_dart(),
            self.native_balance_wei.into_into_dart().into_dart(),
            self.native_balance_eth.into_into_dart().into_dart(),
            self.token_address.into_into_dart().into_dart(),
            self.token_symbol.into_into_dart().into_dart(),
            self.token_decimals.into_into_dart().into_dart(),
            self.token_balance_raw.into_into_dart().into_dart(),
            self.token_balance_formatted.into_into_dart().into_dart(),
            self.explanation.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::ethereum::EthereumDemoResult
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::ethereum::EthereumDemoResult>
    for crate::api::ethereum::EthereumDemoResult
{
    fn into_into_dart(self) -> crate::api::ethereum::EthereumDemoResult {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::libp2p_webrtc::Libp2pWebRtcDialRequest {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.server_multiaddr.into_into_dart().into_dart(),
            self.timeout_seconds.into_into_dart().into_dart(),
            self.message.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::libp2p_webrtc::Libp2pWebRtcDialRequest
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::libp2p_webrtc::Libp2pWebRtcDialRequest>
    for crate::api::libp2p_webrtc::Libp2pWebRtcDialRequest
{
    fn into_into_dart(self) -> crate::api::libp2p_webrtc::Libp2pWebRtcDialRequest {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::libp2p_webrtc::Libp2pWebRtcDialResult {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.local_peer_id.into_into_dart().into_dart(),
            self.remote_peer_id.into_into_dart().into_dart(),
            self.dialed_multiaddr.into_into_dart().into_dart(),
            self.sent_message.into_into_dart().into_dart(),
            self.echoed_message.into_into_dart().into_dart(),
            self.server_timestamp.into_into_dart().into_dart(),
            self.status_message.into_into_dart().into_dart(),
            self.explanation.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::libp2p_webrtc::Libp2pWebRtcDialResult
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::libp2p_webrtc::Libp2pWebRtcDialResult>
    for crate::api::libp2p_webrtc::Libp2pWebRtcDialResult
{
    fn into_into_dart(self) -> crate::api::libp2p_webrtc::Libp2pWebRtcDialResult {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::solana::SolanaDemoRequest {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.rpc_url.into_into_dart().into_dart(),
            self.wallet_address.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::solana::SolanaDemoRequest
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::solana::SolanaDemoRequest>
    for crate::api::solana::SolanaDemoRequest
{
    fn into_into_dart(self) -> crate::api::solana::SolanaDemoRequest {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::solana::SolanaDemoResult {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.rpc_url.into_into_dart().into_dart(),
            self.wallet_address.into_into_dart().into_dart(),
            self.latest_slot.into_into_dart().into_dart(),
            self.block_height.into_into_dart().into_dart(),
            self.epoch.into_into_dart().into_dart(),
            self.transaction_count.into_into_dart().into_dart(),
            self.lamports.into_into_dart().into_dart(),
            self.sol_balance.into_into_dart().into_dart(),
            self.commitment.into_into_dart().into_dart(),
            self.explanation.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::solana::SolanaDemoResult
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::solana::SolanaDemoResult>
    for crate::api::solana::SolanaDemoResult
{
    fn into_into_dart(self) -> crate::api::solana::SolanaDemoResult {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::sui::SuiDemoRequest {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.rpc_url.into_into_dart().into_dart(),
            self.wallet_address.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::sui::SuiDemoRequest
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::sui::SuiDemoRequest>
    for crate::api::sui::SuiDemoRequest
{
    fn into_into_dart(self) -> crate::api::sui::SuiDemoRequest {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::sui::SuiDemoResult {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.rpc_url.into_into_dart().into_dart(),
            self.wallet_address.into_into_dart().into_dart(),
            self.api_version.into_into_dart().into_dart(),
            self.rpc_methods_count.into_into_dart().into_dart(),
            self.current_epoch.into_into_dart().into_dart(),
            self.reference_gas_price.into_into_dart().into_dart(),
            self.active_validators.into_into_dart().into_dart(),
            self.owned_objects_in_page.into_into_dart().into_dart(),
            self.stake_position_count.into_into_dart().into_dart(),
            self.explanation.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::sui::SuiDemoResult
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::sui::SuiDemoResult>
    for crate::api::sui::SuiDemoResult
{
    fn into_into_dart(self) -> crate::api::sui::SuiDemoResult {
        self
    }
}

impl SseEncode for String {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <Vec<u8>>::sse_encode(self.into_bytes(), serializer);
    }
}

impl SseEncode for crate::api::ethereum::EthereumDemoRequest {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <String>::sse_encode(self.rpc_url, serializer);
        <String>::sse_encode(self.wallet_address, serializer);
        <String>::sse_encode(self.erc20_token_address, serializer);
    }
}

impl SseEncode for crate::api::ethereum::EthereumDemoResult {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <String>::sse_encode(self.chain_rpc_url, serializer);
        <String>::sse_encode(self.wallet_address, serializer);
        <String>::sse_encode(self.latest_block_number, serializer);
        <String>::sse_encode(self.native_balance_wei, serializer);
        <String>::sse_encode(self.native_balance_eth, serializer);
        <String>::sse_encode(self.token_address, serializer);
        <String>::sse_encode(self.token_symbol, serializer);
        <u8>::sse_encode(self.token_decimals, serializer);
        <String>::sse_encode(self.token_balance_raw, serializer);
        <String>::sse_encode(self.token_balance_formatted, serializer);
        <String>::sse_encode(self.explanation, serializer);
    }
}

impl SseEncode for crate::api::libp2p_webrtc::Libp2pWebRtcDialRequest {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <String>::sse_encode(self.server_multiaddr, serializer);
        <u32>::sse_encode(self.timeout_seconds, serializer);
        <String>::sse_encode(self.message, serializer);
    }
}

impl SseEncode for crate::api::libp2p_webrtc::Libp2pWebRtcDialResult {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <String>::sse_encode(self.local_peer_id, serializer);
        <String>::sse_encode(self.remote_peer_id, serializer);
        <String>::sse_encode(self.dialed_multiaddr, serializer);
        <String>::sse_encode(self.sent_message, serializer);
        <String>::sse_encode(self.echoed_message, serializer);
        <String>::sse_encode(self.server_timestamp, serializer);
        <String>::sse_encode(self.status_message, serializer);
        <String>::sse_encode(self.explanation, serializer);
    }
}

impl SseEncode for Vec<u8> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(self.len() as _, serializer);
        for item in self {
            <u8>::sse_encode(item, serializer);
        }
    }
}

impl SseEncode for Option<u64> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <bool>::sse_encode(self.is_some(), serializer);
        if let Some(value) = self {
            <u64>::sse_encode(value, serializer);
        }
    }
}

impl SseEncode for crate::api::solana::SolanaDemoRequest {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <String>::sse_encode(self.rpc_url, serializer);
        <String>::sse_encode(self.wallet_address, serializer);
    }
}

impl SseEncode for crate::api::solana::SolanaDemoResult {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <String>::sse_encode(self.rpc_url, serializer);
        <String>::sse_encode(self.wallet_address, serializer);
        <u64>::sse_encode(self.latest_slot, serializer);
        <u64>::sse_encode(self.block_height, serializer);
        <u64>::sse_encode(self.epoch, serializer);
        <Option<u64>>::sse_encode(self.transaction_count, serializer);
        <u64>::sse_encode(self.lamports, serializer);
        <String>::sse_encode(self.sol_balance, serializer);
        <String>::sse_encode(self.commitment, serializer);
        <String>::sse_encode(self.explanation, serializer);
    }
}

impl SseEncode for crate::api::sui::SuiDemoRequest {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <String>::sse_encode(self.rpc_url, serializer);
        <String>::sse_encode(self.wallet_address, serializer);
    }
}

impl SseEncode for crate::api::sui::SuiDemoResult {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <String>::sse_encode(self.rpc_url, serializer);
        <String>::sse_encode(self.wallet_address, serializer);
        <String>::sse_encode(self.api_version, serializer);
        <String>::sse_encode(self.rpc_methods_count, serializer);
        <String>::sse_encode(self.current_epoch, serializer);
        <String>::sse_encode(self.reference_gas_price, serializer);
        <String>::sse_encode(self.active_validators, serializer);
        <String>::sse_encode(self.owned_objects_in_page, serializer);
        <String>::sse_encode(self.stake_position_count, serializer);
        <String>::sse_encode(self.explanation, serializer);
    }
}

impl SseEncode for u32 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        serializer.cursor.write_u32::<NativeEndian>(self).unwrap();
    }
}

impl SseEncode for u64 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        serializer.cursor.write_u64::<NativeEndian>(self).unwrap();
    }
}

impl SseEncode for u8 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        serializer.cursor.write_u8(self).unwrap();
    }
}

impl SseEncode for () {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {}
}

impl SseEncode for i32 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        serializer.cursor.write_i32::<NativeEndian>(self).unwrap();
    }
}

impl SseEncode for bool {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        serializer.cursor.write_u8(self as _).unwrap();
    }
}

#[cfg(not(target_family = "wasm"))]
mod io {
    // This file is automatically generated, so please do not edit it.
    // @generated by `flutter_rust_bridge`@ 2.12.0.

    // Section: imports

    use super::*;
    use flutter_rust_bridge::for_generated::byteorder::{
        NativeEndian, ReadBytesExt, WriteBytesExt,
    };
    use flutter_rust_bridge::for_generated::{Lifetimeable, Lockable, transform_result_dco};
    use flutter_rust_bridge::{Handler, IntoIntoDart};

    // Section: boilerplate

    flutter_rust_bridge::frb_generated_boilerplate_io!();
}
#[cfg(not(target_family = "wasm"))]
pub use io::*;

/// cbindgen:ignore
#[cfg(target_family = "wasm")]
mod web {
    // This file is automatically generated, so please do not edit it.
    // @generated by `flutter_rust_bridge`@ 2.12.0.

    // Section: imports

    use super::*;
    use flutter_rust_bridge::for_generated::byteorder::{
        NativeEndian, ReadBytesExt, WriteBytesExt,
    };
    use flutter_rust_bridge::for_generated::wasm_bindgen;
    use flutter_rust_bridge::for_generated::wasm_bindgen::prelude::*;
    use flutter_rust_bridge::for_generated::{Lifetimeable, Lockable, transform_result_dco};
    use flutter_rust_bridge::{Handler, IntoIntoDart};

    // Section: boilerplate

    flutter_rust_bridge::frb_generated_boilerplate_web!();
}
#[cfg(target_family = "wasm")]
pub use web::*;
